//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalYearProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CivilSuit
    {
        public int SuitId { get; set; }
        public int UserUserId { get; set; }
        public string SuitName { get; set; }
        public string Description { get; set; }
        public string WhichParty { get; set; }
        public string Progress { get; set; }
    
        public virtual User User { get; set; }
    }
}
